[tool.poetry]
name = "N31L"
version = "1.0.0"
description = "N31L is a utilitarian bot for the Call of Duty server."
authors = ["Ethan C <16727756+EthanC@users.noreply.github.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.11,<3.12"
python-dotenv = "^1.0.0"
loguru = "^0.7.2"
loguru-discord = "^1.1.0"
hikari-tanjun = "^2.17.1"
httpx = "0.25.0"
asyncpraw = "^7.7.1"
urlextract = "^1.8.0"
uvloop = {version = "^0.19.0", platform = "linux"}

[tool.poetry.dev-dependencies]
pylint = "^3.0.2"
black = "^23.10.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
