[tool.poetry]
name = "N31L"
version = "1.0.0"
description = "N31L is a utilitarian bot for the Call of Duty server."
authors = ["Ethan C <16727756+EthanC@users.noreply.github.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.11,<3.12"
python-dotenv = "^1.0.0"
loguru = "^0.7.0"
loguru-discord = "^1.0.3"
hikari-tanjun = "^2.16.0"
httpx = "0.24.1"
asyncpraw = "^7.7.1"
uvloop = {version = "^0.17.0", platform = "linux"}

[tool.poetry.dev-dependencies]
pylint = "^2.17.5"
black = "^23.7.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
