[tool.poetry]
name = "N31L"
version = "1.0.0"
description = "N31L is a utilitarian bot for the Call of Duty server."
authors = ["Ethan C <16727756+EthanC@users.noreply.github.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.12,<3.13"
python-dotenv = "^1.0.1"
loguru = "^0.7.2"
loguru-discord = "^1.1.1"
hikari-tanjun = "^2.17.2"
httpx = "0.27.0"
asyncpraw = "^7.7.1"
urlextract = "^1.9.0"
uvloop = {version = "^0.19.0", platform = "linux"}

[tool.poetry.group.dev.dependencies]
ruff = "^0.3.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.ruff.lint]
select = ["I"]
