[tool.poetry]
name = "N31L"
version = "1.0.0"
description = "N31L is a utilitarian bot for the Call of Duty server."
authors = ["Ethan C <16727756+EthanC@users.noreply.github.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.11,<3.12"
loguru = "^0.6.0"
notifiers = "^1.3.3"
hikari-tanjun = "^2.11.4"
httpx = "0.23.3"
asyncpraw = "^7.7.0"
uvloop = {version = "^0.17.0", platform = "linux"}

[tool.poetry.dev-dependencies]
pylint = "^2.16.4"
black = "^23.1.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
